const promptRegistry = [
  {
    id: 1,
    key: "greetingDecision",
    name: "Chief Greeting Officer Decision",
    owner: "ai-decision-engine",
    runtime: true,
    output: "application/json",
    temperature: 1.2,
    modulePath: "./greetingDecision",
  },
  {
    id: 2,
    key: "teapotMusing",
    name: "Teapot Philosophical Musing",
    owner: "teapot-service",
    runtime: true,
    output: "application/json",
    temperature: 1.4,
    modulePath: "../../teapot-service/gemini-musing.js",
  },
  {
    id: 3,
    key: "adrGenerator",
    name: "Architecture Decision Record Generator",
    owner: "offline-build",
    runtime: false,
    output: "text/markdown",
    temperature: 1.0,
    script: "../../../scripts/generate-adrs.js",
  },
  {
    id: 4,
    key: "incidentReportGenerator",
    name: "Incident Report Generator",
    owner: "offline-build",
    runtime: false,
    output: "text/markdown",
    temperature: 1.0,
    script: "../../../scripts/generate-incidents.js",
  },
  {
    id: 5,
    key: "abTestAnalysis",
    name: "A/B Test Analysis Report",
    owner: "ab-testing-service",
    runtime: true,
    output: "application/json",
    temperature: 0.8,
    modulePath: "./abTestAnalysis",
  },
  {
    id: 6,
    key: "systemHealthNarrative",
    name: "System Health Narrative",
    owner: "frontend-via-api",
    runtime: true,
    output: "application/json",
    temperature: 1.4,
    modulePath: "./systemHealthNarrative",
  },
  {
    id: 7,
    key: "securityAudit",
    name: "Security Audit Generator",
    owner: "offline-build",
    runtime: false,
    output: "text/markdown",
    temperature: 0.8,
    script: "../../../scripts/generate-security-audit.js",
  },
];

const adrTopics = [
  "Why we need microservices for Hello World",
  "Selection of Node.js for the API Gateway",
  "Using Gemini AI for greeting word selection",
  "Why Rust is necessary for the punctuation microservice",
  "Spring Boot as the capitalization engine",
  "C# .NET for string concatenation",
  "Python Flask for A/B testing",
  "Go for the HTCPCP teapot health check",
  "React and Next.js for rendering two words",
  "Google Cloud Run as the deployment platform",
  "Firestore as the feature flag database",
  "Redis for caching AI greeting decisions",
  "The decision to A/B test exclamation marks",
  "Rate limiting to 1 request per minute",
  "Using Terraform for infrastructure as code",
  "CI/CD pipeline design for greeting deployment",
  "The on-call rotation policy for Hello World",
  "Monitoring and alerting strategy",
  "Why we need 47 Architecture Decision Records",
  "The greeting word 'Yo' moratorium",
  "Teapot service SLA requirements",
  "Incident severity classification for greetings",
  "Log retention policy for greeting events",
  "Security considerations for the greeting pipeline",
  "GDPR compliance for storing greeting preferences",
  "Accessibility requirements for Hello World",
  "Internationalization strategy (rejected: too useful)",
  "Dark mode support for the greeting display",
  "Font selection for Hello World (took 3 sprints)",
  "The great semicolon debate of 2024",
  "Whether 'World' should be capitalized",
  "Handling the edge case where World doesn't exist",
  "Disaster recovery plan for greeting outages",
  "Multi-region deployment (rejected: too practical)",
  "API versioning strategy (v1 is Hello, v2 is also Hello)",
  "WebSocket support for real-time greeting updates",
  "GraphQL vs REST for the greeting API",
  "Docker base image selection per microservice",
  "The controversial decision to add a period option",
  "Vendor lock-in assessment for Google Cloud",
  "Ethical AI usage policy for greeting decisions",
  "Carbon footprint analysis of saying Hello World",
  "Load testing results (peak: 1 user)",
  "The favicon selection process (3 design reviews)",
  "README.md length requirements (minimum 2000 words)",
  "Whether to open-source the project",
  "Using HTTP 418 as the health check status code",
];

const incidentScenarios = [
  {
    id: "INC-001",
    description: "Greeting displayed 'Hi World' instead of 'Hello World'",
    severity: "P0 - Critical",
    duration: "4 minutes",
    impact: "1 user received an unauthorized casual greeting",
  },
  {
    id: "INC-002",
    description: "Teapot health check accidentally returned HTTP 200",
    severity: "P0 - Critical",
    duration: "12 seconds",
    impact: "The teapot briefly pretended to be a functional server. Identity crisis ensued.",
  },
  {
    id: "INC-003",
    description: "Gemini AI recommended 'Yo' as the greeting",
    severity: "P1 - High",
    duration: "7 minutes",
    impact: "The CGO AI attempted to deploy an unauthorized greeting without board approval.",
  },
  {
    id: "INC-004",
    description: "Exclamation mark missing from 'Hello World'",
    severity: "P2 - Medium",
    duration: "23 minutes",
    impact: "Greeting was displayed without punctuation after the experiment service returned null.",
  },
  {
    id: "INC-005",
    description: "Spring Boot capitalization service took 47 seconds to start",
    severity: "P2 - Medium",
    duration: "47 seconds",
    impact: "Cold start latency exceeded the acceptable greeting delivery time.",
  },
];

module.exports = {
  adrTopics,
  incidentScenarios,
  promptRegistry,
};
